In [1]:
import pandas as pd
from ethnicolr import census_ln, pred_census_ln,pred_wiki_ln

In [18]:
cand_geo = pd.read_csv('../data/cleaned/candidates_surgeo.csv')

C:\Users\samtg\AppData\Local\Temp\ipykernel_11644\1138471954.py:1: DtypeWarning: Columns (12,21,33,37,38,40,41,42,43,44,45,46,51,54) have mixed types. Specify dtype option on import or set low_memory=False.
  cand_geo = pd.read_csv('../data/cleaned/candidates_surgeo.csv')

In [7]:
cand_geo.sample(10)

,ELECTION,OFFICECD,RECIPID,CANCLASS,RECIPNAME,COMMITTEE,FILING,SCHEDULE,PAGENO,SEQUENCENO,...,last_name,zcta5,first_name.1,surname,white,black,api,native,multiple,hispanic
11999,2021,55,2246,P,"Joseph, Rita C",H,12,ABC,NaN,NaN,...,Atkins,11225,ANDRE,ATKINS,0.013507,0.981176,0.000029,0.000131,0.004460,0.000696
7804,2021,55,2423,P,"Vernikov, Inna",H,11,ABC,NaN,NaN,...,Vayser,11230,LEV,VAYSER,NaN,NaN,NaN,NaN,NaN,NaN
7959,2021,55,2308,P,"Pierre, Josue",H,5,ABC,NaN,NaN,...,Charles,11226,ALAN,CHARLES,0.066261,0.899120,0.002495,0.004776,0.010796,0.016552
10207,2021,55,2377,P,"Hollingsworth, Michael D",H,6,ABC,NaN,NaN,...,Schlabs,11206,ERIC,SCHLABS,0.988830,0.000000,0.003510,0.000000,0.007659,0.000000
9789,2021,55,2377,P,"Hollingsworth, Michael D",H,7,ABC,NaN,NaN,...,Meyers,11213,ADAM,MEYERS,0.892872,0.074928,0.000193,0.001599,0.024000,0.006409
2989,2021,55,2306,P,"Aviles, Alexa",H,6,ABC,NaN,NaN,...,Schlabs,11206,ERIC,SCHLABS,0.988830,0.000000,0.003510,0.000000,0.007659,0.000000
7092,2021,55,2332,P,"Hantzopoulos, Evie",H,9,ABC,NaN,NaN,...,Paliura,11030,SPIRODON,PALIURA,NaN,NaN,NaN,NaN,NaN,NaN
9749,2021,55,2377,P,"Hollingsworth, Michael D",H,8,ABC,NaN,NaN,...,McGurk,11225,COLIN,MCGURK,0.914344,0.027235,0.001269,0.000000,0.055504,0.001647
3956,2021,5,1930,P,"Rivera, Carlina",J,5,ABC,NaN,NaN,...,Margeta,10009,DARLENE,MARGETA,NaN,NaN,NaN,NaN,NaN,NaN
8226,2021,55,2308,P,"Pierre, Josue",H,5,ABC,NaN,NaN,...,Mc Ewen,11203,WENDY,MCEWEN,0.150851,0.822797,0.001171,0.001998,0.016790,0.006394

In [24]:
missing_eth = cand_geo[cand_geo['white'].isna()]

In [20]:
cand_geo.shape

(16635, 63)

In [25]:
missing_eth = missing_eth[['RECIPNAME','DATE','REFNO','surname','white','black','api','hispanic','native','multiple']]

In [26]:
test = census_ln(missing_eth,'surname')

In [67]:
pred_wiki_ln(missing_eth,'surname')

c:\Users\samtg\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:81: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

TypeError: Error when deserializing class 'Embedding' using config={'name': 'embedding', 'trainable': True, 'dtype': 'float32', 'input_dim': 1436, 'output_dim': 32, 'embeddings_initializer': {'class_name': 'RandomUniform', 'config': {'minval': -0.05, 'maxval': 0.05, 'seed': None}}, 'embeddings_regularizer': None, 'activity_regularizer': None, 'embeddings_constraint': None, 'mask_zero': False, 'input_length': 20, 'input_shape': [None, 20]}.

Exception encountered: Unrecognized keyword arguments passed to Embedding: {'input_length': 20}

In [27]:
test

,RECIPNAME,DATE,REFNO,surname,white,black,api,hispanic,native,multiple,pctwhite,pctblack,pctapi,pctaian,pct2prace,pcthispanic
0,"Abreu, Adolfo",10/1/2020,R0001855,ABIONA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Abreu, Adolfo",9/28/2020,R0001736,ABREU,NaN,NaN,NaN,NaN,NaN,NaN,16.37,0.72,1.16,0.15,2.27,79.33
2,"Abreu, Adolfo",1/11/2021,R0004034,ACOSTA,NaN,NaN,NaN,NaN,NaN,NaN,8.04,0.69,2.36,0.29,0.63,87.99
3,"Abreu, Adolfo",12/7/2020,R0002655,ACTONBOND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Abreu, Adolfo",1/8/2021,R0003609,ADLER,NaN,NaN,NaN,NaN,NaN,NaN,95.57,0.56,0.49,0.17,1.31,1.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3193,"Lin, Yu",1/7/2021,R0000305,ZHE,NaN,NaN,NaN,NaN,NaN,NaN,71.94,0.00,20.14,3.60,(S),(S)
3194,"Lin, Yu",1/24/2021,R0001102,ZHOU,NaN,NaN,NaN,NaN,NaN,NaN,0.59,0.22,97.96,0.06,0.96,0.22
3195,"Lin, Yu",2/15/2021,R0001329,ZHU,NaN,NaN,NaN,NaN,NaN,NaN,0.73,(S),97.89,(S),1.12,0.14
3196,"Lin, Yu",1/9/2021,R0000327,ZIANG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3197,"Lin, Yu",1/11/2021,R0000398,ZOU,NaN,NaN,NaN,NaN,NaN,NaN,1.14,0.54,96.91,0.00,1.14,0.27

In [28]:
still_missing = test[test['pctwhite'].isna()]

In [29]:
still_missing.shape

(1867, 16)

jobs

In [30]:
cand_geo.columns

Index(['ELECTION', 'OFFICECD', 'RECIPID', 'CANCLASS', 'RECIPNAME', 'COMMITTEE',
       'FILING', 'SCHEDULE', 'PAGENO', 'SEQUENCENO', 'REFNO', 'DATE',
       'REFUNDDATE', 'NAME', 'C_CODE', 'STRNO', 'STRNAME', 'APARTMENT',
       'BOROUGHCD', 'CITY', 'STATE', 'ZIP', 'OCCUPATION', 'EMPNAME',
       'EMPSTRNO', 'EMPSTRNAME', 'EMPCITY', 'EMPSTATE', 'AMNT', 'MATCHAMNT',
       'PREVAMNT', 'PAY_METHOD', 'INTERMNO', 'INTERMNAME', 'INTSTRNO',
       'INTSTRNM', 'INTAPTNO', 'INTCITY', 'INTST', 'INTZIP', 'INTEMPNAME',
       'INTEMPSTNO', 'INTEMPSTNM', 'INTEMPCITY', 'INTEMPST', 'INTOCCUPA',
       'PURPOSECD', 'EXEMPTCD', 'ADJTYPECD', 'RR_IND', 'SEG_IND', 'INT_C_CODE',
       'first_name', 'last_name', 'zcta5', 'first_name.1', 'surname', 'white',
       'black', 'api', 'native', 'multiple', 'hispanic'],
      dtype='object')

In [36]:
employer = cand_geo['EMPNAME'].value_counts()
employer_df = pd.DataFrame(employer)
employer_df.reset_index(inplace=True)

In [41]:
employer_df

                             EMPNAME  count
0                      Self-Employed   1440
1                       Not Employed    540
2                            Retired    232
3                   City of New York    195
4                            NYC DOE    158
...                              ...    ...
4638  Office of the Attorney General      1
4639                     New Visions      1
4640              Gettysburg College      1
4641         Queens botanical garden      1
4642                 Fada Group Inc.      1

[4643 rows x 2 columns]

In [42]:
job = cand_geo['OCCUPATION'].value_counts()
job_df = pd.DataFrame(job)
job_df.reset_index(inplace=True)

In [62]:
job_df.head(15)

            OCCUPATION  count
0           Unemployed   1344
1              Retired   1155
2         Not Employed    595
3             Attorney    579
4              Student    486
5              Teacher    418
6           Consultant    259
7    Software Engineer    255
8            Homemaker    191
9              Manager    184
10            Director    184
11              Lawyer    172
12           Professor    140
13  Executive Director    111
14           Physician    104

In [46]:
from sockit.title import clean, search, sort
import json

In [63]:
title = 'Software Engineer'

In [64]:
socs = search(title)

In [65]:
socs

{}

In [66]:
print(json.dumps(sort(socs), indent=2))

[]